// @ts-check

import { Heap } from '../heap.js';

// 題目鏈結
// https://leetcode.com/problems/task-scheduler

// 題目說明
// Given a characters array tasks, representing the tasks a CPU needs to do, where each letter represents a different task. Tasks could be done in any order. Each task is done in one unit of time. For each unit of time, the CPU could complete either one task or just be idle.
// However, there is a non-negative integer n that represents the cooldown period between two same tasks (the same letter in the array), that is that there must be at least n units of time between any two same tasks.
// Return the least number of units of times that the CPU will take to finish all the given tasks.
//

// Example 1:
// Input: tasks = ["A","A","A","B","B","B"], n = 2
// Output: 8
// Explanation:
// A -> B -> idle -> A -> B -> idle -> A -> B
// There is at least 2 units of time between any two same tasks.
//

// Example 2:
// Input: tasks = ["A","A","A","B","B","B"], n = 0
// Output: 6
// Explanation: On this case any permutation of size 6 would work since n = 0.
// ["A","A","A","B","B","B"]
// ["A","B","A","B","A","B"]
// ["B","B","B","A","A","A"]
// ...
// And so on.
//

// Example 3:
// Input: tasks = ["A","A","A","A","A","A","B","C","D","E","F","G"], n = 2
// Output: 16
// Explanation:
// One possible solution is
// A -> B -> C -> A -> D -> E -> A -> F -> G -> A -> idle -> idle -> A -> idle -> idle -> A
//

// Constraints:
// 1 <= task.length <= 10⁴
// tasks[i] is upper-case English letter.
// The integer n is in the range [0, 100].
//

// 解題重點
// 1.
// 2.

// 解題思路
// 1.
// 2.

/**
 * Solution :
 *
 * 複雜度
 * Time Complexity : O(??)
 * Space Complexity: O(??)
 */

/**
 * @param {string[]} tasks
 * @param {number} n
 * @return {number}
 */
var leastIntervalMaxHeap = function (tasks, n) {
  const cnt = new Array(26).fill(0);

  for (let i = 0, n = tasks.length; i < n; i++) {
    const cur = tasks[i];
    const idx = cur.charCodeAt(0) - 65;
    cnt[idx] += 1;
  }

  // 根據出現頻率(or數量)以大到小排序。
  const maxHeap = new Heap((a, b) => a > b);
  for (const num of cnt) {
    if (num > 0) {
      maxHeap.push(num);
    }
  }
  // 時間鎖
  const queue = [];

  let time = 0;

  while (!maxHeap.isEmpty() || queue.length > 0) {
    time += 1;
    if (!maxHeap.isEmpty()) {
      let newCnt = maxHeap.pop() - 1;
      if (newCnt > 0) {
        queue.push([newCnt, time + n]);
      }
    }
    if (queue.length > 0 && queue[0][1] === time) {
      maxHeap.push(queue.shift()[0]);
    }
  }

  return time;
};

/**
 * Solution :
 *
 * 計算出理論上的上限，因為當離散程度夠大時，就不需要擔心任務的間隔時間不夠，導致"Idle"發生。
 * 所以最終答案是 max(理論上限長度, 實際任務長度)。
 *
 * 複雜度
 * Time Complexity : O(??)
 * Space Complexity: O(??)
 */

/**
 * @param {string[]} tasks
 * @param {number} n
 * @return {number}
 */
var leastInterval = function (tasks, n) {
  const cnt = new Array(26).fill(0);

  let maxCnt = -1;

  for (let i = 0, n = tasks.length; i < n; i++) {
    const cur = tasks[i];
    const idx = cur.charCodeAt(0) - 65;
    cnt[idx] += 1;

    if (cnt[idx] > maxCnt) {
      maxCnt = cnt[idx];
    }
  }

  let count = (maxCnt - 1) * (n + 1); // group size * slot size
  let upper_bound = cnt.reduce(
    (pre, cur) => pre + (cur === maxCnt ? 1 : 0),
    count
  ); // count + p
  return Math.max(upper_bound, tasks.length); // 理論上限與tasks實際大小，取兩者較大者。
};

// 測試
(function () {
  console.log('Testing [p0621_taskScheduler]...');

  const testingWith = (cb) => {
    console.log(`Testing ${cb.name}`);
    console.log(cb(['A', 'A', 'A', 'B', 'B', 'B'], 2) === 8);
    console.log(cb(['A', 'A', 'A', 'B', 'B', 'B'], 0) === 6);
    console.log(
      cb(['A', 'A', 'A', 'A', 'A', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], 2) === 16
    );
    console.log(
      cb(
        [
          'F',
          'J',
          'J',
          'A',
          'J',
          'F',
          'C',
          'H',
          'J',
          'B',
          'E',
          'G',
          'G',
          'F',
          'A',
          'C',
          'I',
          'F',
          'J',
          'C',
          'J',
          'C',
          'H',
          'C',
          'A',
          'D',
          'G',
          'H',
          'B',
          'F',
          'G',
          'C',
          'C',
          'A',
          'E',
          'B',
          'H',
          'J',
          'E',
          'I',
          'F',
          'D',
          'E',
          'A',
          'C',
          'D',
          'B',
          'D',
          'J',
          'J',
          'C',
          'F',
          'D',
          'D',
          'J',
          'H',
          'A',
          'E',
          'C',
          'D',
          'J',
          'D',
          'G',
          'G',
          'B',
          'C',
          'E',
          'G',
          'H',
          'I',
          'D',
          'H',
          'F',
          'E',
          'I',
          'B',
          'D',
          'E',
          'I',
          'E',
          'C',
          'J',
          'G',
          'I',
          'D',
          'E',
          'D',
          'J',
          'C',
          'A',
          'C',
          'C',
          'D',
          'I',
          'J',
          'B',
          'D',
          'H',
          'H',
          'J',
          'G',
          'B',
          'G',
          'A',
          'H',
          'E',
          'H',
          'E',
          'D',
          'E',
          'J',
          'E',
          'J',
          'C',
          'F',
          'C',
          'J',
          'G',
          'B',
          'C',
          'I',
          'I',
          'H',
          'F',
          'A',
          'D',
          'G',
          'F',
          'C',
          'C',
          'F',
          'G',
          'C',
          'J',
          'B',
          'B',
          'I',
          'C',
          'J',
          'J',
          'E',
          'G',
          'H',
          'C',
          'I',
          'G',
          'J',
          'I',
          'G',
          'G',
          'J',
          'G',
          'G',
          'E',
          'G',
          'B',
          'I',
          'J',
          'B',
          'H',
          'D',
          'H',
          'G',
          'F',
          'C',
          'H',
          'C',
          'D',
          'A',
          'G',
          'B',
          'H',
          'H',
          'B',
          'J',
          'C',
          'A',
          'F',
          'J',
          'G',
          'F',
          'E',
          'B',
          'F',
          'E',
          'B',
          'B',
          'A',
          'E',
          'F',
          'E',
          'H',
          'I',
          'I',
          'C',
          'G',
          'J',
          'D',
          'H',
          'E',
          'F',
          'G',
          'G',
          'D',
          'E',
          'B',
          'F',
          'J',
          'J',
          'J',
          'D',
          'H',
          'E',
          'B',
          'D',
          'J',
          'I',
          'F',
          'C',
          'I',
          'E',
          'H',
          'F',
          'E',
          'G',
          'D',
          'E',
          'C',
          'F',
          'E',
          'D',
          'E',
          'A',
          'I',
          'E',
          'A',
          'D',
          'H',
          'G',
          'C',
          'I',
          'E',
          'G',
          'A',
          'H',
          'I',
          'G',
          'G',
          'A',
          'G',
          'F',
          'H',
          'J',
          'D',
          'F',
          'A',
          'G',
          'H',
          'B',
          'J',
          'A',
          'H',
          'B',
          'H',
          'C',
          'G',
          'F',
          'A',
          'C',
          'C',
          'B',
          'I',
          'G',
          'G',
          'B',
          'C',
          'J',
          'J',
          'I',
          'E',
          'G',
          'D',
          'I',
          'J',
          'I',
          'C',
          'G',
          'A',
          'J',
          'G',
          'F',
          'J',
          'F',
          'C',
          'F',
          'G',
          'J',
          'I',
          'E',
          'B',
          'G',
          'F',
          'A',
          'D',
          'A',
          'I',
          'A',
          'E',
          'H',
          'F',
          'D',
          'D',
          'C',
          'B',
          'J',
          'I',
          'J',
          'H',
          'I',
          'C',
          'D',
          'A',
          'G',
          'F',
          'I',
          'B',
          'E',
          'D',
          'C',
          'J',
          'G',
          'I',
          'H',
          'E',
          'C',
          'E',
          'I',
          'I',
          'B',
          'B',
          'H',
          'J',
          'C',
          'F',
          'I',
          'D',
          'B',
          'F',
          'H',
          'F',
          'A',
          'C',
          'A',
          'A',
          'B',
          'D',
          'C',
          'A',
          'G',
          'B',
          'G',
          'F',
          'E',
          'G',
          'A',
          'A',
          'A',
          'C',
          'J',
          'H',
          'H',
          'G',
          'C',
          'C',
          'B',
          'C',
          'E',
          'B',
          'E',
          'F',
          'I',
          'E',
          'E',
          'D',
          'I',
          'H',
          'G',
          'F',
          'A',
          'H',
          'B',
          'J',
          'B',
          'G',
          'H',
          'C',
          'C',
          'B',
          'G',
          'C',
          'B',
          'A',
          'E',
          'G',
          'A',
          'J',
          'G',
          'D',
          'C',
          'I',
          'G',
          'F',
          'G',
          'G',
          'A',
          'J',
          'E',
          'I',
          'D',
          'E',
          'A',
          'F',
          'A',
          'H',
          'C',
          'E',
          'D',
          'D',
          'D',
          'H',
          'I',
          'F',
          'F',
          'A',
          'F',
          'A',
          'A',
          'C',
          'J',
          'D',
          'J',
          'H',
          'I',
          'F',
          'A',
          'C',
          'B',
          'C',
          'A',
          'C',
          'C',
          'H',
          'A',
          'J',
          'I',
          'B',
          'A',
          'I',
          'F',
          'J',
          'C',
          'I',
          'B',
          'C',
          'E',
          'E',
          'E',
          'J',
          'G',
          'F',
          'E',
          'I',
          'A',
          'A',
          'E',
          'B',
          'J',
          'H',
          'H',
          'H',
          'A',
          'H',
          'J',
          'E',
          'F',
          'E',
          'F',
          'G',
          'J',
          'D',
          'I',
          'D',
          'I',
          'F',
          'B',
          'J',
          'D',
          'A',
          'A',
          'D',
          'F',
          'G',
          'B',
          'J',
          'H',
          'F',
          'A',
          'D',
          'H',
          'C',
          'B',
          'A',
          'J',
          'H',
          'I',
          'F',
          'H',
          'E',
          'G',
          'B',
          'A',
          'F',
          'F',
          'A',
          'C',
          'D',
          'G',
          'I',
          'I',
          'J',
          'H',
          'H',
          'C',
          'J',
          'G',
          'B',
          'A',
          'D',
          'B',
          'F',
          'J',
          'D',
          'I',
          'A',
          'F',
          'F',
          'F',
          'F',
          'A',
          'E',
          'B',
          'C',
          'G',
          'H',
          'E',
          'B',
          'B',
          'A',
          'G',
          'D',
          'C',
          'C',
          'E',
          'A',
          'C',
          'F',
          'G',
          'A',
          'I',
          'F',
          'B',
          'H',
          'J',
          'G',
          'C',
          'B',
          'H',
          'D',
          'A',
          'H',
          'B',
          'H',
          'H',
          'C',
          'A',
          'F',
          'I',
          'C',
          'F',
          'A',
          'C',
          'J',
          'I',
          'H',
          'H',
          'F',
          'B',
          'B',
          'D',
          'E',
          'C',
          'J',
          'F',
          'C',
          'E',
          'A',
          'J',
          'E',
          'C',
          'A',
          'E',
          'B',
          'A',
          'J',
          'F',
          'J',
          'J',
          'J',
          'H',
          'H',
          'C',
          'I',
          'E',
          'G',
          'G',
          'H',
          'J',
          'J',
          'H',
          'H',
          'H',
          'J',
          'H',
          'A',
          'G',
          'I',
          'C',
          'E',
          'C',
          'D',
          'G',
          'G',
          'F',
          'H',
          'D',
          'G',
          'H',
          'A',
          'E',
          'I',
          'D',
          'A',
          'H',
          'G',
          'E',
          'A',
          'B',
          'F',
          'I',
          'C',
          'A',
          'F',
          'B',
          'A',
          'I',
          'F',
          'G',
          'I',
          'F',
          'D',
          'A',
          'B',
          'J',
          'B',
          'D',
          'F',
          'G',
          'J',
          'J',
          'A',
          'A',
          'C',
          'H',
          'G',
          'F',
          'B',
          'I',
          'I',
          'J',
          'A',
          'H',
          'D',
          'F',
          'E',
          'F',
          'J',
          'B',
          'F',
          'C',
          'G',
          'E',
          'A',
          'G',
          'H',
          'E',
          'H',
          'H',
          'F',
          'I',
          'G',
          'C',
          'C',
          'G',
          'J',
          'B',
          'H',
          'F',
          'H',
          'D',
          'I',
          'B',
          'D',
          'I',
          'F',
          'H',
          'I',
          'D',
          'F',
          'G',
          'G',
          'E',
          'A',
          'C',
          'A',
          'G',
          'H',
          'G',
          'H',
          'J',
          'F',
          'D',
          'F',
          'G',
          'D',
          'D',
          'C',
          'J',
          'C',
          'J',
          'G',
          'G',
          'G',
          'G',
          'H',
          'H',
          'G',
          'D',
          'E',
          'H',
          'G',
          'C',
          'B',
          'F',
          'I',
          'F',
          'C',
          'H',
          'J',
          'I',
          'A',
          'F',
          'D',
          'C',
          'F',
          'C',
          'E',
          'E',
          'D',
          'D',
          'C',
          'G',
          'B',
          'F',
          'E',
          'J',
          'C',
          'I',
          'E',
          'D',
          'B',
          'B',
          'I',
          'I',
          'I',
          'H',
          'C',
          'E',
          'C',
          'J',
          'F',
          'G',
          'A',
          'I',
          'J',
          'D',
          'I',
          'C',
          'G',
          'F',
          'I',
          'E',
          'I',
          'E',
          'F',
          'A',
          'G',
          'E',
          'J',
          'A',
          'I',
          'A',
          'D',
          'A',
          'G',
          'J',
          'F',
          'E',
          'D',
          'I',
          'A',
          'E',
          'J',
          'I',
          'C',
          'J',
          'B',
          'F',
          'B',
          'E',
          'C',
          'E',
          'F',
          'G',
          'E',
          'J',
          'J',
          'I',
          'E',
          'D',
          'F',
          'C',
          'H',
          'H',
          'B',
          'G',
          'D',
          'I',
          'I',
          'F',
          'B',
          'G',
          'C',
          'F',
          'J',
          'B',
          'G',
          'J',
          'H',
          'D',
          'G',
          'C',
          'C',
          'I',
          'I',
          'E',
          'I',
          'B',
          'H',
          'B',
          'I',
          'G',
          'F',
          'H',
          'G',
          'C',
          'J',
          'D',
          'C',
          'E',
          'G',
          'F',
          'C',
          'H',
          'D',
          'A',
          'C',
          'D',
          'H',
          'B',
          'C',
          'H',
          'I',
          'B',
          'A',
          'J',
          'C',
          'B',
          'D',
          'J',
          'D',
          'H',
          'F',
          'B',
          'A',
          'G',
          'G',
          'J',
          'I',
          'E',
          'F',
          'A',
          'D',
          'H',
          'D',
          'B',
          'C',
          'A',
          'H',
          'F',
          'G',
          'B',
          'F',
          'H',
          'B',
          'H',
          'I',
          'J',
          'D',
          'H',
          'I',
          'B',
          'C',
          'D',
          'G',
          'A',
          'E',
          'A',
          'A',
          'I',
          'F',
          'I',
          'F',
          'B',
          'B',
          'I',
          'F',
          'A',
          'E',
          'I',
          'A',
          'B',
          'G',
          'C',
          'F',
          'I',
          'A',
          'F',
          'I',
          'D',
          'H',
          'B',
          'I',
          'I',
          'B',
          'J',
          'F',
          'E',
          'B',
          'B',
          'B',
          'D',
          'C',
          'J',
          'E',
          'J',
          'J',
          'G',
          'D',
          'F',
          'F',
          'F',
          'G',
          'I',
          'H',
          'J',
          'J',
          'G',
          'D',
          'G',
          'F',
        ],
        8
      ) === 1000
    );
  };

  testingWith(leastIntervalMaxHeap);
  testingWith(leastInterval);

  console.log('All Testing Passed ✅');
})();
